### ISSUE TITLE
'Import from twitch user' doesn't import anything 

### ISSUE THREAD

**Issue by sigau** [maweki/twitchlive-extension#102]
Hello !
First thanks for the extension !
I'm on ubuntu 22.04 and I'm using the extension since a little time evereything was working fine. But recently a saw that some of the streamers I was following was not show on the extension and try to import them with user but some of them were still missing. After reinstalling my computer and then the extension I have no more streamers show ( logical still here) but when I try to import from user nothing happen.

**Comment by maweki** [comment]
Can you check which extension version you're on?

**Comment by sigau** [comment]
Hi 
I'm running the version 39 of the extension

**Comment by maweki** [comment]
Okay. So I think you're on the old api version. The change is here:

https://github.com/maweki/twitchlive-extension/commit/7a812b2d3beda8bf1e29ac72838130ebfcfc4748

But it hasn't been backported to a gnome before 43 or 45. You can try to apply the changes yourself. Otherwise, can you tell me your shell version and I can try to backport it and make a branch here.

**Comment by maweki** [comment]
the gnome shell version, i.e. the exact gnome version.

**Comment by sigau** [comment]
oh sorry the gnome version is 42.9

**Comment by maweki** [comment]
Try replacing your `api.js` and `prefs.js` from here: https://github.com/maweki/twitchlive-extension/tree/gnome-42

that's the `gnome-42` branch.

**Comment by sigau** [comment]
So I replace my api.js and prefs.js with the one in the gnome-42 branch and got the following error : 

The settings of extension TwitchLive_Panel@extensions.maweki.de had an error:
```
Error: Requiring Soup, version 3.0: Typelib file for namespace 'Soup', version '3.0' not found
```

Stack trace:
```
@/home/gdebaeck/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/prefs.js:11:14
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by maweki** [comment]
Sorry, I branched from the wrong place. Can you please try it again. I've rebased the `gnome-42` branch

**Comment by sigau** [comment]
Work like a charm now 
thank you very much !

**Comment by maweki** [comment]
For posterity: I've uploaded a package from that branch to ego for shell versions 40-42.
