### ISSUE TITLE
Make setting many streamers more comfortable

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#11]
For more than a few streamers, having this single input field isn't very nice. Maybe we could add some alternative. Maybe a tree-view or something like this.

**Comment by RaphaelRochet** [comment]
Work in progress  ...
![capture d ecran de 2016-05-18 16-40-37](https://cloud.githubusercontent.com/assets/1675389/15362962/4bb1c652-1d17-11e6-8105-ef65c7264f73.png)

**Comment by maweki** [comment]
this is nice.

Some implementations have an empty editable field at the bottom.

**Comment by RaphaelRochet** [comment]
I pushed this in *settings-enh* branch. Can you give it a try ?

**Comment by maweki** [comment]
Ok, I tried it. I think the cells could be editable, then we could do something like this from gtk3-demo:

![bildschirmfoto von 2016-05-19 13-51-48](https://cloud.githubusercontent.com/assets/613272/15392658/e7cd49e2-1dc8-11e6-8e91-d789faa16606.png)

We could do away even with the two buttons if we had an empty cell at the end. This wouldn't even need any code changes for the extension itself, since empty streamer names are ignored.
Deleting could be done via context-menu or a delete-button for every item in a second column.

Somehow I don't really like the single input-field to add a new streamer. What do you think?

**Comment by RaphaelRochet** [comment]
That'd be nice. Hope we'll be able to have the empty cell to always stay at bottom, even if user change sort order.

**Comment by RaphaelRochet** [comment]
Seems editable cells are easy to add. Let's go !

**Comment by RaphaelRochet** [comment]
Editable cells done (12db0d0) but I can't manage to add a _clickable_ image on each row.
While working on it I added an icon for streamers. (f9f9b11) Could be nice to put real streamers icon here later ;)

Next I'll remove the input-field and instead add an empty line if I can give it focus and set it to edit mode.

**Comment by maweki** [comment]
Just deleting any empty cell that is not the last might be alright. Then you just click the cell and press delete.

**Comment by RaphaelRochet** [comment]
One step done : no more GtkEntry, add is done in the list. 
Also, when all cell content is deleted, the streamer gets removed.

I tried to connect on the treeview's key-release event but as you said it's fired also while editing the text !

The two buttons could be made icon-only by using ToolButtons instead, if you think they're too big.

**Comment by maweki** [comment]
I've added preliminary icon support. But there's a cleaner Implementation with a GtkTreeModelFilter instead of a two-column store.

**Comment by RaphaelRochet** [comment]
Nice !
I think this implementation is clean enough. It's just icons ...

**Comment by maweki** [comment]
Don't mind some icons not being available. I'll rewrite the Icons module a bit in master and add download triggers once we've merged the streamer selection into master.

**Comment by RaphaelRochet** [comment]
Merge done.
