### ISSUE TITLE
Have panel display-settings

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#12]
We'd need the following drop-down-settings

Display-Mode: [Cycle (default), All online, Number online]

Streamer-Display: [Name only, Icon and name, Icon only]

And it should work that way. So one could have just the list of icons of the active streamers.

**Comment by maweki** [comment]
I am currently writing this one. @RaphaelRochet once I push the branch, can you handle the settings-side of things?

We would remove the "show count" option and replace it with a drop-down of several options

**Comment by maweki** [comment]
and maybe we should then rename all the stuff. I forgot the name "panel"

**Comment by RaphaelRochet** [comment]
Yep I can do it, if you give me a few days ;)

**Comment by maweki** [comment]
Yeah, of course. Just wanted to ping you on that because the preferences is more your thing. I will improve upon the extension.js-code but if you can provide the settings-strings and translation stubs, that would be grand.

**Comment by RaphaelRochet** [comment]
Done :) Also moved the code so that setting can be changed on the fly.

**Comment by maweki** [comment]
I think this looks great and is a good feature. I'll merge, push, and release it this week.

**Comment by maweki** [comment]
Let's just keep it this way. I'll do the merging and my translations and we're good to go.

**Comment by RaphaelRochet** [comment]
Ok. Let me do the translations rebase stuff.

**Comment by maweki** [comment]
do it on master

**Comment by RaphaelRochet** [comment]
Ok. I saw your answer a bit late and worked it on titlebar, but then I rebased it add squash changes in master.
