### ISSUE TITLE
St.Label sometimes report wrong width

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#13]
![69f7f812-16fe-11e6-838b-a3654a8a16ce](https://cloud.githubusercontent.com/assets/613272/15223981/5e31445a-1877-11e6-9aa6-00d1e40d2377.png)
![6ff78308-1704-11e6-9f03-10d1815a6f99](https://cloud.githubusercontent.com/assets/613272/15223982/5e55e396-1877-11e6-880e-a45be8c910ff.png)

If you are affected, please report your Distribution, gnome-shell-version and clutter-version as well as anything you might have noticed.

**Comment by RaphaelRochet** [comment]
Arch, Gnome 3.20, Clutter 1.26

**Comment by RaphaelRochet** [comment]
Maybe use a fixed width for viewer count, and a min-width for streamer name and game could be a acceptable workaround for this to ?

**Comment by RaphaelRochet** [comment]
Noticed today : IF menu is open while updating THEN widths are correct ! Maybe some off-screen drawing is responsible for wrong width ...
