### ISSUE TITLE
Settings-separator appears iconsistently

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#15]
The seperator sometimes is there and sometimes is not. Maybe it just appears after all the api-requests are done. Maybe we don't even need the separator.

**Comment by maweki** [comment]
![bildschirmfoto von 2016-05-16 00-41-19](https://cloud.githubusercontent.com/assets/613272/15277257/f64281b2-1afe-11e6-8f28-638bcd3d8c7f.png)
![bildschirmfoto von 2016-05-16 00-41-14](https://cloud.githubusercontent.com/assets/613272/15277258/f65c21da-1afe-11e6-8cb3-c44b9e30243d.png)

**Comment by RaphaelRochet** [comment]
I think I fixed this in 1ece2692 . Can you confirm ?

**Comment by maweki** [comment]
No. Still is an issue. When clicking "Update Now" it disappears after it goes from "updating..." back to "Update Now". After re-opening the streamer menu, it re-appears.

**Comment by RaphaelRochet** [comment]
Ok. will fix it now.

**Comment by RaphaelRochet** [comment]
Please test now with b952411
I couldn't reproduce the bug but this should fix the behavior.

**Comment by maweki** [comment]
I consistently see no separator.
![bildschirmfoto von 2016-05-16 01-30-20](https://cloud.githubusercontent.com/assets/613272/15277471/cb421066-1b05-11e6-944b-99c8b600ad1e.png)

**Comment by RaphaelRochet** [comment]
Yes it's hidden when nobody is streaming. As the "Nobdy ..." test is grayed out, I though the separator was not needed. Is that wrong ?

**Comment by maweki** [comment]
Yeah, it's good this way :)
