### ISSUE TITLE
"Nobody Streaming" might be shown twice

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#16]
Already nobody streaming and then clicking update

![bildschirmfoto von 2016-05-16 01-10-21](https://cloud.githubusercontent.com/assets/613272/15277395/1ae82720-1b03-11e6-8224-be871ef97579.png)

**Comment by maweki** [comment]
Clicking "Update now" makes the second one disappear. Closing and re-opening the menu makes it re-appear.

**Comment by RaphaelRochet** [comment]
A bug that cause empty menu is visible since this tweak. I am trying to fix it.

**Comment by RaphaelRochet** [comment]
I think it's good with c6db26f20d95b2e19482834afd123e605e8fb2f3.
