### ISSUE TITLE
Invalidate Icon Cache

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#17]
Streamers update their icons. Mogrify gets installed. There should be some algorithm, some way to invalidate/clear the icon cache. Maybe a button in the settings menu, maybe some automatic mechanism.

**Comment by RaphaelRochet** [comment]
For mogrify not being installed, maybe we should test if it ``/usr/bin/mogrify``is executable and never download anything that's not 'png'.

With twitch api, do you have any hint about streamers changing their icon ? Maybe a way to retrieve their last profile change date ? Maybe that would mean change the way streamers are stored in settings, like a serialized array of objects, to be able to add data like last icon download date.

:thought_balloon:  *More thinking needed*

**Comment by maweki** [comment]
As far as I can see, the filename given in the channel object is actually unique. So we could download and keep the original name and symlink the name for the icon-widget to use.

**Comment by RaphaelRochet** [comment]
Ah, nice one :)

**Comment by RaphaelRochet** [comment]
Question: will the Gtk.IconTheme detect that link target had changed ?

**Comment by maweki** [comment]
> Question: will the Gtk.IconTheme detect that link target had changed ?

possibly not immediately but soon enough. I mean, otherwise we would delete the old icon and switch it with one with an identical name. That's basically the same thing as switching a symlink.

Gtk possibly watches the directories with icons for changes because if no icon is present and an icon is made available, the correct icon is loaded almost immediately.

**Comment by RaphaelRochet** [comment]
Sound good :+1: . You work on it ?

**Comment by maweki** [comment]
Not now. I won't be getting anything done codewise for the next few days. Feel free to pick up anything you like. I will be doing another release at the end of the week, I think.

I've added some stubs of how I think the Icon-lib could work like to the `icons-enh` branch.

**Comment by maweki** [comment]
So, I've done most of what we've talked about, including some refactoring, extracting the Twitch api calls.

What's missing:
* If we can't write to the .cache-directory, all the stuff should be disabled
* the check whether `mogrify` is available should be cached
* Icon downloading/converting still doesn't happen async
* `trigger_download_by_name` needs a http session to work, which isn't nice.
* `_retrieveStreamerIcons` in the settings is implemented but not yet called at the appropriate times.

If you want to tackle any of that, feel free to do so.

**Comment by maweki** [comment]
PR #22 should solve this. We don't invalidate the icon cache but save the unique icons, making it possible to find out, when an Icon has changed.

**Comment by maweki** [comment]
Invalidate the icon cache is no longer necessary since we only download what we need, when we need it and also check the twich-api for icon updates.

The main thought was doing this in order to receive updated streamer icons.

**Comment by RaphaelRochet** [comment]
There's a tiny issue left however : old streamer icons will stay there. Not much a matter but not clean ;)
