### ISSUE TITLE
Sort streams

### ISSUE THREAD

**Issue by RaphaelRochet** [maweki/twitchlive-extension#20]
As promises does asynch requests, the order is currently random-like.

We should add on option to sort streams by streamer name, game, or viewer count.

**Comment by maweki** [comment]
I had a nice patch but somehow after a bit of time no streamers were shown in the menu (but still in the panel) :(

**Comment by RaphaelRochet** [comment]
Please see comments on commit 4a80fcd094459234c8afcac9e32bcc156be50cde

**Comment by RaphaelRochet** [comment]
Possible cause : your this.online array is empty during a check. If we open the menu at this time, it will be empty.
The online array that is being populated should be different than the array used to draw the menu, so that we always have the latest complete set.

**Comment by RaphaelRochet** [comment]
Maybe sorting may be done at that moment too, so that rotation is not changed when the menu is opened.

**Comment by maweki** [comment]
Thanks for the hints. Fixed the issues.

**Comment by RaphaelRochet** [comment]
Are you still working on this ?

**Comment by maweki** [comment]
Besides the preliminary work I've done, i have yet to do anything. If you want to pick it up, feel free to do so. Then I wouldn't have to learn how to add combo boxes to the ui XML file.

**Comment by RaphaelRochet** [comment]
Here it is ;) Hopefully I could bind the combobox to settings with just a few JS lines.
