### ISSUE TITLE
GLib-CRITICAL When changing something in the streamer settings

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#21]
when adding, removing or changing something in the new streamer listing, this happens in the user's journal (`journalctl --user --follow`):

`(gnome-shell:2196): GLib-CRITICAL **: Source ID 13312 was not found when attempting to remove it`

**Comment by RaphaelRochet** [comment]
There's somewhere a code that removes a source and does not zeroes the linked variable. Should be easy to fix ;)

**Comment by RaphaelRochet** [comment]
Sorry for the delay
