### ISSUE TITLE
Support/Hide(?) playlists

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#24]
Streamers are able to stream playlists, basically restreams of former streams or VoDs.

The stream-object is still available with the attribute `"is_playlist": true`. But playlist streaming isn't, for example, supported by `livestreamer`. Also, the streamer is not live per se.

So I think we need to do one or both of those two things:

* Have a settings entry to hide playlist streams
* Distinguish playlist streams from normal streams, maybe changing the person-icon (usually representing the viewer but maybe also "in person") to maybe a harddisk or document icon, to represent that this is something created previously.

**Comment by maweki** [comment]
One of my streamers has been playlisting the whole day and it starts to get on my nerves. Expect a fix very soon and included in the next release.

**Comment by maweki** [comment]
Maybe this way?

![bildschirmfoto von 2016-06-08 21-07-30](https://cloud.githubusercontent.com/assets/613272/15907341/101f823a-2dbd-11e6-95ce-eb2205885f1d.png)

**Comment by RaphaelRochet** [comment]
:+1:

**Comment by maweki** [comment]
I think we still might want to do the second thing.

**Comment by RaphaelRochet** [comment]
Yep. But it's the easiest ;)

**Comment by maweki** [comment]
Ok, I think we're done here.
