### ISSUE TITLE
Before initialization of streamers, extension icon says "Twitch Streamers"

### ISSUE THREAD

**Issue by torpet** [maweki/twitchlive-extension#25]
This takes away a large amount of space in the tray bar. I think the best thing to do here would be to either just show the twitch icon only or a twitch icon with 3 dots next to it (to suggest initialization to the user)?

**Comment by maweki** [comment]
The text was a remnant from before we had our own Icons. So I guess this is a good idea.

**Comment by RaphaelRochet** [comment]
I must say +1 on this.
A bit annoying to have all indicators left to twitchlive-extension to move a few seconds after init.
