### ISSUE TITLE
Hide channel if streamer is streaming playlist

### ISSUE THREAD

**Issue by torpet** [maweki/twitchlive-extension#26]
One of the streamers I follow sometimes streams playlists. (DansGaming)
I think most people wouldn't want to see this in the list of streams.

This also causes problems with livestreamer, which just doesn't open the stream:
> error: No streams found on this URL: twitch.tv/DansGaming

The Twitch API returns the following: https://gist.github.com/torpet/74860dd7fea61c4f6168d23013cd3826

All that has to be done is to check whether `is_playlist` is false.

**Comment by RaphaelRochet** [comment]
It's already done in current dev version ;)

**Comment by torpet** [comment]
Sorry, should have checked.
