### ISSUE TITLE
Exception by spawn if binary does not exist?

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#28]
While trying #23 , I found that curl was not installed in my virtualized debian box. Instead of returning false/error-codes/something for `spawn` for `curl`, there was an exception, halting all the operations.

This possibly happens with mogrify not being installed as well and the mogrify-check that I implemented possibly does not even work.

**Comment by RaphaelRochet** [comment]
Maybe the cleanest solution would be to check for existence and correct mode (+x) on the mogrify binary ?

**Comment by maweki** [comment]
> Maybe the cleanest solution would be to check for existence and correct mode (+x) on the mogrify binary ?

But where is it? Do we need to check with `which` beforehand? Or do we only check with `which`? Would that be enough?

**Comment by RaphaelRochet** [comment]
We need to make both tests. Get path and, if valid, check for exec righ.

I'd do it the GLib way, with ``GLib.find_program_in_path`` and ``GLib.file_test``.

**Comment by maweki** [comment]
The documentation says "Locates the first *executable*", implying that the rights are allready correct. Also, which/bash autocompletion etc. only check for +x files in the path. So I think we can just test with `GLib.find_program_in_path` and be done.

**Comment by RaphaelRochet** [comment]
You're right. My bad.

**Comment by RaphaelRochet** [comment]
Do we need to check this and add a warning in the settings ? Or is the warning in metadata/readme enough (as it does not break the core functionality - only icons) ?

**Comment by maweki** [comment]
Since it both does not impact functionality that much, I think the warning in the Readme is enough. I also think that, at least for curl, almost everybody has that installed. This was just a weird corner case since I've done the most minimal debian installation and have not installed any package before testing.

**Comment by RaphaelRochet** [comment]
Ok ;)
