### ISSUE TITLE
Use twitch API to obtain followers

### ISSUE THREAD

**Issue by mcat95** [maweki/twitchlive-extension#29]
First, thanks for the extension. It's simply awesome.

But, it could be even more awesome if you could use your twitch username to sync your followers of your account. The good part is that an OAuth login is not necessary, because the followers are public access.

The relevant method can be found [here](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-channelschannelfollows)

A task to sync the extension with the saved account name every ~2-3 days would be great

If you are OK with it, I can open a pull request :smile:

**Comment by maweki** [comment]
> First, thanks for the extension. It's simply awesome.
Thank you. We've been hard at work :)

> if you could use your twitch username to sync your followers of your account
That's a nice idea in principle.

> A task to sync the extension with the saved account name every ~2-3 days would be great

That I think we'd rather not do. Also, there's no good mechanism to do that in a consistent manner. I rather we add a button in the settings "add follows from user" with a small dialogue where users enter a username and press "ok/add" and all that user's follows are added and we put some deduplication-functionality to settings (we need it only on saving - on reload, it's deduplicated automagically). That way, I can add my follows and my girlfriend/boyfriend's follows to the living-room-box and if I update my followings, I can, on occasion, "manually" "sync".

Would that be a solution you'd be fine with?

**Comment by RaphaelRochet** [comment]
> Edit: That also means, we wouldn't track deletions/removals

A simple "Remove all" button next to the list should do the job ;)

**Comment by maweki** [comment]
> Would that be a solution you'd be fine with?

@RaphaelRochet  Would that be a solution we'd be fine with?

**Comment by RaphaelRochet** [comment]
It would be perfect for me.

**Comment by maweki** [comment]
All right. Then there are three things:

* A remove-all/clear-button that empties the streamer list
* A piece of code that does not allow duplicate streamers to be saved
* An "add follows from user" button that opens a dialogue/message-box (I'd prefer it this way than another entry field that's always visible) where one can enter a username and all the follows are added to the streamerlist (this needs adding another endpoint to api.js)

**Comment by mcat95** [comment]
Completely agree with you. I will open a PR in a few days

**Comment by maweki** [comment]
I looked at the API. We get a maximum of 100 follows and then would have to do pagination. I think 100 is enough.

**Comment by RaphaelRochet** [comment]
Also, having more than 100 resuests done every 5 mins or so wouldn't be a good thing anyway !

**Comment by mcat95** [comment]
The only thing I don't quite understand is what do you mean by `A piece of code that does not allow duplicate streamers to be saved **(while still allowing duplicate entries to be added)**`

**Comment by RaphaelRochet** [comment]
In other words : duplicates must be removed on save.
