### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by RaphaelRochet** [maweki/twitchlive-extension#3]
I could do it if nobody isn't already working on it. Please assign the issue to me if it's ok.
I will provide French translation as well.

**Comment by maweki** [comment]
Please, feel free to do so. I'll add a German translation once I've merged your pull request.

**Comment by RaphaelRochet** [comment]
OK. Expect a pull request very soon ;)

**Comment by RaphaelRochet** [comment]
Nb: sorry, I forgot that only collaborators on a project can be assigned an issue. My bad.
