### ISSUE TITLE
'Command to Execute' will not work with multiple commands. (VLC and Chatty) 

### ISSUE THREAD

**Issue by hexdsl** [maweki/twitchlive-extension#36]
I want to use this extension to launch VLC and Chatty as this is my preferred setup to do this logically i would have thoughts something like: 

chatty -channel %streamer% -connect && livestreamer -p vlc http://twitch.tv/%streamer% best 

(tried &&, &, ;) 

No matter what variation of command i use the extension only sees the first command not the second. is there a work around for this ?

**Comment by RaphaelRochet** [comment]
You can work around this issue by calling a shell with a command line :
```
/bin/sh -c "chatty -channel %streamer% -connect && livestreamer -p vlc http://twitch.tv/%streamer% best"
```

**Comment by maweki** [comment]
You can also extract this command into a shellscript with the streamer as a parameter and call it like `/path/to/script %streamer%`

**Comment by hexdsl** [comment]
> You can also extract this command into a shellscript with the streamer as a parameter and call it like /path/to/script %streamer%

Yep. this IS the solution i have come to. thanks :)
