### ISSUE TITLE
Twitchlive no longer working

### ISSUE THREAD

**Issue by RaphaelRochet** [maweki/twitchlive-extension#39]
Hi all,

Twitch is now forcing us to add an application ID.

We will fix Twitchlive soon. 

More info :
https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843

**Comment by RaphaelRochet** [comment]
@maweki You are the owner ... could you register Twitchlive with your Twitch Account ? 
(I can do it if for whatever reason you don't)

**Comment by RaphaelRochet** [comment]
In 3c2b161 I added a Client ID I made, it seems to be enough for the API to work.
Is it working for you ?

**Comment by maweki** [comment]
Yes. That works fine. I add it immediately and do a release.

**Comment by maweki** [comment]
So the release has been done about 12 hours ago. I am still waiting for the review process to go through.

**Comment by RaphaelRochet** [comment]
I have an extension waiting for review since last Saturday :disappointed: ...

**Comment by maweki** [comment]
I'll wait until sunday and then I'll contact "the authorities". I am a now responsible for extension community management at the gnome foundation. So I'll look into this process as well.

**Comment by maweki** [comment]
Well, I've got a review that suggested the user should enter a client id himself. I am currently appealing this decision since that is certainly not how oauth works.

**Comment by RaphaelRochet** [comment]
Yep client id is not an oauth token !

**Comment by maweki** [comment]
So apparently without me receiving any additional mail, my appeal has gone through and the current version should work.
