### ISSUE TITLE
Upgraded to Ubuntu GNOME 17.04, configuration window not opening

### ISSUE THREAD

**Issue by NikPaulussen** [maweki/twitchlive-extension#41]
I recently upgraded to Ubuntu GNOME 17.04 from 16.10 and now whenever I want to open the settings window of TwitchLive, it just dumps this:
```
Error: Requiring St, version none: Typelib file for namespace 'Clutter', version '0' not found

Stack trace:
  @/home/nik/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/icons.js:5:7
  @/home/nik/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/prefs.js:13:7
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

Found out that the upgrade sometimes uninstalls `gir1.2-clutter-1.0`, but that specific package (and `gir1.2-clutter-gst-3.0, gir1.2-gtkclutter-1.0` are already installed on my system. As I don't know any further what to do I'm opening a bug report here.

Greetings, Nik o/

**Comment by asiantuntija** [comment]
I can confirm this, just fresh Ubuntu GNOME 17.04 and getting the same error.

**Comment by maweki** [comment]
I hate the idea of having to install Ubuntu and debug the issue but I try to do it over the course of the next week.

**Comment by maweki** [comment]
Can you see whether this fixes your problem?

https://micheleg.github.io/dash-to-dock/news/2017/04/23/ubuntu-settings-error-clutter.html

**Comment by NikPaulussen** [comment]
@maweki That was the first source I found :D 
But no, that does not fix the problem, because like I said in my first post the package is already installed.

**Comment by maweki** [comment]
@NikPaulussen oh, ok. Sorry. I am currently a bit under the weather.

I try to look into it as soon as possible

**Comment by terzag** [comment]
Have the same issue (on Ubuntu 17.04 too), gir1.2-clutter-1.0 and gir1.2-clutter-3.0 are both installed.

**Comment by RaphaelRochet** [comment]
I've got that issue on Arch too. Fixed by removing useless St import in icons.js :
Remove that line at the beginning : ```const St = imports.gi.St;```

**Comment by RaphaelRochet** [comment]
I've updated the master branch with that fix (#18d9ff14e87e7ea4e89f7e342d4a887bfd6f18a1). Please test :)

**Comment by NikPaulussen** [comment]
Yep, works for me. Nice. :3 
Not closing this because I don't know how this problem is affecting others and if this quick fix works for everyone.

**Comment by RaphaelRochet** [comment]
Yep, that's why I didn't close this. Waiting for other's feedback.

Le ven. 12 mai 2017 à 15:03, Nik Paulussen <notifications@github.com> a
écrit :

**Comment by terzag** [comment]
Has it been updated on extensions.gnome.org or do we have to install the new version manually from GitHub? (Haven't tested yet.)

**Comment by RaphaelRochet** [comment]
You have to do it manually

**Comment by terzag** [comment]
I've never installed an extension manually, what's the proper way to do it? I assume I'd have to clone the GIT repo and put it in ~/.local/share/gnome-shell/extensions with a specific name?

**Comment by RaphaelRochet** [comment]
You can download a zip here https://github.com/maweki/twitchlive-extension/archive/master.zip and extract it your extensions folder, ie : 
```~/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/```

**Comment by terzag** [comment]
Ok. Just did it and I can confirm too that the settings window now opens on Ubuntu GNOME 17.04.

**Comment by maweki** [comment]
Okay. I'm gonna do a release with that patch.

**Comment by terzag** [comment]
Should I open a new bug report for the non-working indicator or is it linked to the change? I.e. now that the prefs dialog is working, does it display anything for other people (on Ubuntu)?

**Comment by maweki** [comment]
Yeah, please file a new bug for that and we'll see.

**Comment by maweki** [comment]
Seems like the import wasn't that unused after all

https://github.com/maweki/twitchlive-extension/blob/18d9ff14e87e7ea4e89f7e342d4a887bfd6f18a1/icons.js#L85

Can we import conditionally?
