### ISSUE TITLE
Indicator not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by terzag** [maweki/twitchlive-extension#42]
Using Ubuntu 17.04.

I've installed the Twitchlive indicator with the new version that fixes the broken prefs dialog. I have never used the extension before, so not sure if I'm doing something wrong.

What happens is that after adding a bunch of channels in the prefs (i Imported the ones I follow from my account), the indicator stays grey and in its menu, I have what appears to be a blank line, then the settings and then a greyed out entry "Updating..." (or something similar, my system is in french).

I've tried reloading the shell (Alt + F2 and r) after adding and configuring the extension, also quit and restarted the session.

Uploaded a capture of the menu just in case (I find the empty line quite odd): http://imgur.com/a/l4x9K

**Comment by maweki** [comment]
It seems the data is not retrieved correctly, which is quite strange since importing from your profile basically uses the same routines.

Please start `journalctl --user -f` in your terminal and restart the shell. Look for any error or info messages regarding the extensions. There we might find some hint of what's going on

**Comment by terzag** [comment]
When I start journalctl --user -f, I get "No journal files were found." and then nothing happens in the terminal when I restart the shell.

I've tried dmesg after restarting just in case but nothing related to the extension there.

**Comment by RaphaelRochet** [comment]
Hi;
I think this is related to #41 fix unfortunately.
Log says : " An error occured : ReferenceError: St is not defined"

**Comment by terzag** [comment]
I'm using the fixed version. Do you mean it fixed the prefs window but broke something else?

**Comment by RaphaelRochet** [comment]
Yes. Seems "St" is already defined when called from prefs but not from extension ....

**Comment by maweki** [comment]
The preferences somehow run in a different import context. We had this discussion on the gnome side some months ago where people where using some clutter helper functions and the clutter namespace wasnt available in some contexts.

Let's conditionally import St.

**Comment by RaphaelRochet** [comment]
You know how to do that ?

**Comment by maweki** [comment]
Well, what if we added the `const St = ...` to the top of the single function using that import. I mean, we aren't actually importing anything. We just bind the name.

We don't need to bind it for the whole file.

**Comment by RaphaelRochet** [comment]
That worked :)
What I tried is :
```let icon = new imports.gi.St.Icon({ icon_name: get_icon_name(streamername), style_class: style_class });```

**Comment by maweki** [comment]
That's fine as well since it's only one reference. Good job! Let's get that to e.g.o

**Comment by RaphaelRochet** [comment]
You do the tiny fix ?

**Comment by maweki** [comment]
yeah, ok

**Comment by maweki** [comment]
ok. I've put the new version up at e.g.o.

**Comment by terzag** [comment]
Can confirm that it seems to work. :)
