### ISSUE TITLE
Show streamer uptime

### ISSUE THREAD

**Issue by AccountOneOff** [maweki/twitchlive-extension#52]
Is it possible to add streamer uptime to the menu?

**Comment by maweki** [comment]
Do you know whether this data is available somewhere through the API?

**Comment by AccountOneOff** [comment]
No, I don't unfortunately. However, [FrankerFaceZ](https://github.com/FrankerFaceZ/FrankerFaceZ) is somehow able to manage it.

**Comment by maweki** [comment]
So, apparently this is part of the API. There's a `created_at` field for nearly all entities and for streams this about corresponds to the uptime.

https://discuss.dev.twitch.tv/t/question-about-created-at/7145

We already grab the streams-endpoint so this wouldn't be too too much of a problem and wouldn't need another request.
