### ISSUE TITLE
Update API endpoint

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#53]
We're still using the v3 API. We should be using the new API: https://dev.twitch.tv/docs/api/

**Comment by maweki** [comment]
Yeah, so this is now broken. Just changing kraken und helix doesn't work.

**Comment by maweki** [comment]
* Okay, so we need to get the active streamers using `https://api.twitch.tv/helix/streams/?user_login=` with up to 100 users as parameters.
* The `game_id` needs to be resolved to get the game name
* The `user_id` needs to be used to retrieve the streamer icon

Here's an example response

```
$ curl -H "Client-ID: 4yzkpoa13a9zqepwguxejohaqulrgbu" https://api.twitch.tv/helix/streams/?user_login=yogscast
{"data":[{"id":"35378541104","user_id":"20786541","user_name":"Yogscast","game_id":"497434","type":"live","title":"Total War: Warhammer 2 w/ Tom \u0026 Ben!","viewer_count":2106,"started_at":"2019-08-21T16:01:55Z","language":"en","thumbnail_url":"https://static-cdn.jtvnw.net/previews-ttv/live_user_yogscast-{width}x{height}.jpg","tag_ids":["6ea6bca4-4712-4ab9-a906-e3336a9d8039"]}],"pagination":{"cursor":"eyJiIjpudWxsLCJhIjp7Ik9mZnNldCI6MX19"}}
```

**Comment by zikeji** [comment]
@maweki I've created a PR using the updated API. See #56

See my comments in the PR - I realize this isn't perfect.

**Comment by maweki** [comment]
Thanks to #56, we're now using the new API. Thank you for your contribution.
