### ISSUE TITLE
Mixer version

### ISSUE THREAD

**Issue by LuciousLisa** [maweki/twitchlive-extension#54]
I've fallen completely in love with this extension, it's amazing to keep track of some streams I wouldn't want to miss. Thank you so much for creating/maintaining it!  
That said, there's also some Mixer channels I'd like to follow in the same way. So here's me asking: could you _possibly pretty please with a cherry on top_ look into (re)creating it for Mixer?

**Comment by maweki** [comment]
I didn't even know what Mixer was or that it existed. The API seems to be quite similar. I'm looking into this.

**Comment by maweki** [comment]
I'll update this issue/post as I go along with research.

* I need to apply for a client id https://watchbeam.zendesk.com/hc/en-us/articles/360002814491-Developer-Registration-and-Agreement
*  We can't retrieve a user's subscriptions as this needs authentication
* There's no difference between channel and stream
* all other necessary data seems to be included in the `/channels` endpoint
* Streamericons are available from the avatarUrl property of the channel

**Comment by azizLIGHT** [comment]
This can probably be closed. Mixer is gone now

**Comment by LuciousLisa** [comment]
Agreed.
