### ISSUE TITLE
Shows no-one streaming while there are subscribed streams online

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [maweki/twitchlive-extension#59]
It would appear that twitch's API has changed, Im not seeing any online streamers even when the site shows them as online

**Comment by maweki** [comment]
Have you updated the extension to the newest version? We've already switched to the newest API endpoint since about three weeks ago.

**Comment by A-UNDERSCORE-D** [comment]
Im stuck on the compat version (ubuntu 18.04 still uses gnome-shell v3.28.4) which I did reinstall recently, but so far no dice. Want me to do another reinstall?

**Comment by maweki** [comment]
> Im stuck on the compat version

Oh. That's a problem. A reinstall won't help here. Basically the new commits that are needed are 9d9529230f808ec5cf9f7a1934eace14604f26da and 3c956060f044b1f48b0616291c82253570d341c5

They might be easy to backport. I could try this in a few hours but I would rely on you to test this if you don't do the backport yourself.

**Comment by A-UNDERSCORE-D** [comment]
I'm good with being a guinea pig--I would do the port myself but I don't know js all that well. Thanks for letting me know at the very least

**Comment by maweki** [comment]
Update: The patches do not apply cleanly. I try to look into this over the weekend.

**Comment by A-UNDERSCORE-D** [comment]
Thanks, let me know if/when you need a tester, and thanks for looking into it

**Comment by sciencywolf** [comment]
Any progress about this issue? I'm also affected by this problem (same configuration Ubuntu 18.04, gnome-shell 3.28.4 and twitchlive-extension 3.30-compat).

**Comment by maweki** [comment]
@sciencywolf I didn't (and apparently nobody else either) really have the time but I suspect backporting is not too hard. It just isn't working automatically.

But thanks for reminding me. Maybe I can do it this weekend.

**Comment by maweki** [comment]
Okay @sciencywolf @A-UNDERSCORE-D 

you can try out the 3.30-helix-wip branch.

**Comment by A-UNDERSCORE-D** [comment]
Done, appears to work, streamer icons are missing from the bar though (they show up in the settings panel)

Thanks for the quick update

**Comment by maweki** [comment]
Okay. This now seems to work. I have updated the readme. I will close this issue now. If there's anything not working (I've already fixed clicking on the menu items). The correct branch is now `3.30-helix`.
