### ISSUE TITLE
GNOME 3.36 Update

### ISSUE THREAD

**Issue by guitaristtom** [maweki/twitchlive-extension#64]
This broke with GNOME 3.36 update and just continuously errors out.

**Comment by maweki** [comment]
What did they break now? Do you see any error in `journalctl --user`? Maybe with `-f`?

**Comment by guitaristtom** [comment]
>What did they break now?

I _heard_ that it was a fair bit, but it might have just been visually. I'm not about for extensions and behind the scenes.

Looks like I get quite a bit of spam of this:
```
updateData/</<@/home/thomas/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/extension.js:280:11
                                            Promise/this._handle/<@/home/thomas/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/promise.js:48:23
```
![Screenshot from 2020-04-04 11-35-10](https://user-images.githubusercontent.com/6890628/78458730-69af6480-7668-11ea-86d4-7eefc53409df.png)

**Comment by maweki** [comment]
We no longer distribute the promise.js file. I think you can just delete it. It must be a leftover from a previous installation. I am working on the other issues but debugging is really really annoying.

**Comment by maweki** [comment]
I think I fixed this now. Can you try master?

**Comment by justkotti** [comment]
Works well now
Thank you

**Comment by maweki** [comment]
This is fixed and works now. :)
