### ISSUE TITLE
Show Oauth status

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [maweki/twitchlive-extension#68]
The recently added oauth button does appear to work, but it does not show any status post-oauth

**Comment by maweki** [comment]
You will see an error message (or not) in the "Update" field in the dropdown menu. I hoped this was enough. If anything didn't work, you'd see it there. But yeah, maybe a field showing the status of the token would be nice.

**Comment by A-UNDERSCORE-D** [comment]
Ah okay. Stlll seems to be hanging on updating for me, but I'll give it an hour or two

**Comment by maweki** [comment]
You could try logging out and back in again. Maybe there's an issue with picking up the token. I had a similar problem but I thought it was because I did an update.

**Comment by A-UNDERSCORE-D** [comment]
Tried an `alt+f2 r` to restart gracefully, that appears to have worked. Thanks!

Also for reference I installed your about 5 mins before I created this issue

**Comment by A-UNDERSCORE-D** [comment]
Okay closing this as you have that. Thanks again for the speedy update!

**Comment by maweki** [comment]
Debugging shell extensions is incredibly tedious and I hope to fix this soon. But your token should be valid 60 days.

**Comment by A-UNDERSCORE-D** [comment]
Noted, and it should be reasonably simple to notice when it expires, based on the panel not updating
