### ISSUE TITLE
Right-align viewer count

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#7]
This is just a small bugbear and it should be easy to fix. Well, I spent an hour on it without getting anywhere.

For posterity and because of lack of any documentation besides arcane knowledge handed down from extension to extension:

> (2016-05-05 19:55:22) ebassi:
> maweki: St.Label does not support text-align, so you can use a St.Bin and pack the St.Label into it using the alignment attributes

With better tooling and documentation, this would be a low-hanging fruit.

**Comment by RaphaelRochet** [comment]
Look how I did it in https://github.com/RaphaelRochet/arch-update :

```
		let box = new St.BoxLayout({ vertical: false, style_class: 'panel-status-menu-box' });
		this.label = new St.Label({ text: '',
			y_expand: true,
			y_align: Clutter.ActorAlign.CENTER });

		box.add_child(this.updateIcon);
		box.add_child(this.label);
		this.actor.add_child(box);
```

**Comment by maweki** [comment]
I don't see how that x-aligns the label to the right.

**Comment by RaphaelRochet** [comment]
Oops, wrong issue. Sorry.

**Comment by maweki** [comment]
I don't know whether this is the best idea, but it works
