### ISSUE TITLE
Unauthorized (OAuth token is missing)

### ISSUE THREAD

**Issue by Paralusion** [maweki/twitchlive-extension#70]
The new OAuth method does not seem to work for me. Not sure where it's going wrong, but it gives this error and nothing else.

Unauthorized (OAuth token is missing)

**Comment by maweki** [comment]
Did you get to complete the OAuth-Process?

I know that for some reason the token isn't picked up right away (#69 ). Does logging out and logging in again fix the issue?

**Comment by Paralusion** [comment]
I'm not sure how I would be able to complete the OAUTH process. One day it stopped working, the other I had to update it and as far as I can remember, it has been like this since. Triggering the "Unaothired (OAuth token is missing) button makes it say "Updating ...", but it just jumps back to the same message. There has never been a moment where I was prompted to sign into anything.

**Comment by maweki** [comment]
You can complete the oauth-process from the options-menu.

**Comment by Paralusion** [comment]
I see. I haven't noticed that button in the options menu, which is my fault. I've successfully performed the OATH process by going to the options menu and clicking the button. 

Thanks for your help and my apologies for my oversights.
