### ISSUE TITLE
Gnome Shell 3.38(.1) support

### ISSUE THREAD

**Issue by CubeTheThird** [maweki/twitchlive-extension#74]
This extension does not seem to work as of version 3.38 of Gnome Shell.

**Comment by CubeTheThird** [comment]
Here is the log from the system output:

Extension TwitchLive_Panel@extensions.maweki.de: ImportError: No JS module 'tweener' found in search path
                                                @/home/user/.local/share/gnome-shell/extensions/TwitchLive_Panel@extensions.maweki.de/extension.js:15:17
                                                _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:420:13
                                                loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27
                                                _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
                                                collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                                _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
                                                _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
                                                _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
                                                init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                                _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
                                                start@resource:///org/gnome/shell/ui/main.js:159:5
                                                @<main>:1:47

**Comment by maweki** [comment]
Nibbler fixed that with #73

I will upload a new version today

GNOME really sucks for developers and it is extremely buggy, but sadly there's no real alternative.

**Comment by CubeTheThird** [comment]
Ah cool. Didn't see that.
Supposedly the next major release is supposed to overhaul the experience for developing extensions, providing tools to help upgrade them between releases and whatnot. We'll see what comes out of that though.

**Comment by maweki** [comment]
> Supposedly the next major release is supposed to overhaul the experience for developing extensions

The lack of documentation and unstable API (if you want to call monkey-patching the JS-engine that) make this a pain. I don't need upgrading tools. I need a documentation. But I was at GUADEC twice and you just fall on deaf ears talking to the shell core developers. And the people paid by Red Hat were the worst about that. "Extensions are not the GNOME experience", "Extensions are basically the wild west".

Anyways, I hope you like the extension. I did the release now. I'll close this issue and cross my fingers, that I don't have to care in the coming weeks or months.

**Comment by CubeTheThird** [comment]
Ya Documentation is one of the main focuses for this. I'm referencing this blog post (amongst other sources) : https://blogs.gnome.org/sri/2020/09/16/the-gnome-extensions-rebooted-initiative/

**Comment by maweki** [comment]
Yeah, and if you look at the GUADEC presentation, documentation has an asterisk and a big IF. I had this talk with Sri before and I don't think anything will come from it. I am glad @Nibbler999 has the nerves to keep up. I don't.
