### ISSUE TITLE
Bad Request (Malformed query params.)

### ISSUE THREAD

**Issue by fearsembrace** [maweki/twitchlive-extension#77]
Running Ubuntu 20.04.2 LTS and gnome 3.36.8. Installing from Firefox with the gnome plugin. Other extensions work fine, and this one installs. I'm able to click OAuth authentication, and it does take me through those steps, and I click the final link "To finish OAuth-Process click here". However, I still have the "Bad Request (Malformed query params.)" error showing in the drop down.

**Comment by maweki** [comment]
Do you get an oauth token in `~/.cache/twitchlive/`?

**Comment by fearsembrace** [comment]
I do. I even moved it out of that directory to see if a new one would get created, and it did.

I do have streamers added already.
