### ISSUE TITLE
Add update-now-button

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#8]
If the pc is put to sleep and the update time is quite long, it won't update the data right away. Two possible solutions:

* wake every second and calculate timeout yourself via timestamp calculation
* add an update button to force a manual update

If #5 is being done, this could be right beside it.

![bildschirmfoto von 2016-05-10 09-12-51](https://cloud.githubusercontent.com/assets/613272/15138350/6a474242-168f-11e6-88d1-4750f8eb1b6c.png)

**Comment by RaphaelRochet** [comment]
Aren't extensions re-enabled on resume ?

**Comment by maweki** [comment]
Not on every setup. On my desktop machine, I have disabled locking the screen when the screen turns off. Now if the screen turns off because of inaction, the extensions are disabled anyways. If you force it into hibernation though, without inactivity, the extensions aren't disabled because the screen is neither locked nor is the shell put into inactive mode. If you come back from that setup, you aren't greeted with the clock-overlay.

**Comment by RaphaelRochet** [comment]
Ok. Maybe there's some signal or file we can connect to in order to act on resume. I will dig in that way.

**Comment by maweki** [comment]
If we make space for a settings-button anyways, we can add a manual update button. Should not be an issue this way.

**Comment by RaphaelRochet** [comment]
Menu item introduced by a1db1cc0f44da67de10516ae20cdcd8be8e7e1ff

**Comment by maweki** [comment]
Is it possible to keep the menu open when the button is clicked? Having the label change to "updating..." is very nice.

**Comment by RaphaelRochet** [comment]
That'd be nice. I tried a few tricks but none worked. I'll look at it later, time to sleep for now !

**Comment by maweki** [comment]
Openweather does it by having buttons that react to the clicked event.

**Comment by RaphaelRochet** [comment]
Ok. Seems we really need to use buttons for this, as menuitems always close the menu.
So "update now" and settings should become buttons, grouped in a button box.

**Comment by maweki** [comment]
I don't know whether this looks presentable but I think "emblem-synchronizing-symbolic" is ok for update now. And during the update-process, we could switch between "network-transmit-symbolic" and "network-receive-symbolic" every half a second, if there is no way to spin the synchronize-button.

**Comment by RaphaelRochet** [comment]
There's a ``AnimatedIcon`` class available. I will try to use it !

**Comment by maweki** [comment]
Strange enough, clicking a streamer's name in the panel no longer closes the menu for me...

**Comment by RaphaelRochet** [comment]
Neither it does for me. The scroll tweak and/or the late update may be responsible for this. There's investigation to do there !

**Comment by maweki** [comment]
Give me a few minutes. I will bisect the issue. Maybe it gives us a hint on how to abuse that to achieve the result.

**Comment by maweki** [comment]
Yeah, the issue was introduced in d48a88f735042420ef2f645ace7994be2754d109

**Comment by RaphaelRochet** [comment]
That scroll tweak uses some menuitems' actor and thus bypasses some signal/events. That's the point :)

**Comment by maweki** [comment]
We can abuse this to not let the update-button close the menu, but clicking a streamer's icon should and then the user should see some indicator that the command is being executed (like in the gnome-shell example extension)

**Comment by RaphaelRochet** [comment]
Ok. I will work on this if you don't.

**Comment by maweki** [comment]
Feel free to do so.

**Comment by RaphaelRochet** [comment]
I added a line to close menu(0080c2d).
I will try now to apply the same scheme on update menuitem.

**Comment by RaphaelRochet** [comment]
Please try d47fbde. The menu should be closed now.

**Comment by RaphaelRochet** [comment]
Please try d47fbde. The menu should NOT be closed now !

**Comment by maweki** [comment]
We've done that and it works :)
