### ISSUE TITLE
OAuth Not Working, Bad Request (Malformed query params.)

### ISSUE THREAD

**Issue by z00kiee** [maweki/twitchlive-extension#87]
Setting up OAuth give me Bad Request (Malformed query params.) even after setting up OAuth and updating it still give me the same error

resetting GNOME shell with `alt+f2+r` also still give me the same bad request comment
![Screenshot from 2022-01-05 03-51-05](https://user-images.githubusercontent.com/67544305/148215489-80868570-24e7-436a-b8ba-a5887f4ee63a.png)

OS: Fedora 35
DE: GNOME 41
Twitchlive version: 37

**Comment by maweki** [comment]
Could you look into the token file in `~/.cache/twitchlive`. Please don't post the login token in full. But maybe there's something suspicious there. It would also be great to add a log output to the source file about here:

https://github.com/maweki/twitchlive-extension/blob/master/api.js#L138

maybe `log(url);` and look for something suspicious there. Are you using a Proxy by any chance? I think we've recently broken that functionality.

**Comment by z00kiee** [comment]
> Are you using a Proxy by any chance?

No, but I'm using Firefox Multi-Account Containers and Amazon Container, but I disabled Amazon Container and Multi-Account to make sure noting is blocking the OAuth. I also have no firewall setup.

> Could you look into the token file in **oauth_token**

Yes and still noting I even notice every time I do the OAuth the `oauth_token` do change the token that is generated as it normally does, however I still get the same error

>But maybe there's something suspicious there. It would also be great to add a log output to the source file about here:
https://github.com/maweki/twitchlive-extension/blob/master/api.js#L138

>Edit: It's also possible, that one of your streamers has a strange name (did you enter them manually?) and you have to add the internal streamer name and not the external one. Some streamers (asian ones, for example) have vanity names in their own language and english internal handles.

You're right because I was adding the URL of the twitch channel and not the of the twitch channel.
