### ISSUE TITLE
Doesn't work in gnome 42

### ISSUE THREAD

**Issue by corngoblin** [maweki/twitchlive-extension#89]
After updating to fedora 36 the extension no longer works.

**Comment by maweki** [comment]
Oh not again. can you try just adding the appropriate shell version to the metadata.json file?

**Comment by corngoblin** [comment]
Adding "42.1" fixed it. Thanks!

**Comment by LuciousLisa** [comment]
It didn't work for me. Please update the extension for us, I really miss having it!

**Comment by twidi** [comment]
> It didn't work for me. Please update the extension for us, I really miss having it! Ubuntu 22.04.1 LTS Gnome 42.2

did you try to add 42.2 instead of 42.1? It worked for me (had to logout/log back in)

**Comment by LuciousLisa** [comment]
> did you try to add 42.2 instead of 42.1? It worked for me (had to logout/log back in)

I did.  

@maweki: An update would be greatly appreciated, not just for me, but also for users who don't have a previously existing install to edit and fall back on.

**Comment by maweki** [comment]
So sorry guys, got a newborn at home. I haven't forgotten you. I'll try to do it this weekend.

Maybe someone could do a PR with the correct versions. I won't manage to test it though.

**Comment by maweki** [comment]
I believe I did it! Maybe someone could try it out?!

**Comment by LuciousLisa** [comment]
> I believe I did it! Maybe someone could try it out?!

You sure did! Thanks so much, works a charm now on my machine. :+1: 

Congrats on the new baby btw, enjoy!

**Comment by maweki** [comment]
Great. Thanks. I'm closing this now. It would be great if someone could test it out with the next shell version early. I'm currently lagging a bit behind.
