### ISSUE TITLE
Suggestion : Extension's own icons !

### ISSUE THREAD

**Issue by RaphaelRochet** [maweki/twitchlive-extension#9]
What about using some more obvious icons for the indicator ?

![twitchlive_on](https://cloud.githubusercontent.com/assets/1675389/15162739/e41e881c-1704-11e6-9187-93f5eb9d5a38.png)
![twitchlive_off](https://cloud.githubusercontent.com/assets/1675389/15162744/e6f5bbf0-1704-11e6-8181-8d61d1cbe3b8.png)

SVG files attached :
[icons.tar.gz](https://github.com/maweki/twitchlive-extension/files/258142/icons.tar.gz)

**Comment by maweki** [comment]
Nice one! Thank you very much :)
