### ISSUE TITLE
Error after upgrading to Gnome Shell 43

### ISSUE THREAD

**Issue by CubeTheThird** [maweki/twitchlive-extension#94]
Currently, the "Update" button now shows this message:

> undefined (httpSession.queue_message is not a function)

I do not see any other apparent messages in my system logs.

My gnome version is:
gnome-shell 1:43.1-1

**Comment by corngoblin** [comment]
Have this issue as well after adding "43.1" to the metadata file.

**Comment by maweki** [comment]
We already had a fix and I neglected to upload the new version to ego. Please update and report.

**Comment by CubeTheThird** [comment]
The latest update fixes the issue for me.
