### ISSUE TITLE
"Hide status line from the menu" doesn't work

### ISSUE THREAD

**Issue by doxxedd** [maweki/twitchlive-extension#95]
Upon toggling the setting, the currently live streamers get hidden for just about a second after which all of them are shown in the status bar again.

**Comment by maweki** [comment]
This setting doesn't do what you think it does:

![image](https://user-images.githubusercontent.com/613272/201422169-236b868a-c65c-427d-b36a-4ad60212b171.png)

And if the status line is hidden:

![image](https://user-images.githubusercontent.com/613272/201422269-f7a5c6a7-19b7-45e7-b288-934413f02a2b.png)

Maybe you want to change the panel display mode?
