### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by maweki** [maweki/twitchlive-extension#99]
The same spiel as every year

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by corngoblin** [comment]
I'm worried about these changes and some of the extensions I might lose because of it..

I hope moving twitchlive over goes smoothly for you. That is, if you choose to continue the extension. (I hope you do)

**Comment by maweki** [comment]
Thank you. The changes look straightforward. There were certainly more difficult migrations.

That being said, it always binds resources. And as a volunteer, life often comes in the way. I'll try to do this stuff next week.

**Comment by maweki** [comment]
#101
